services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Your_password123
      MYSQL_DATABASE: BudgetExpenseSystem
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=Your_password123"]
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConnectionDefault=Server=db;Database=BudgetExpenseSystem;User=root;Password=Your_password123;Allow User Variables=true
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh", "-c", "dotnet ef database update && dotnet BudgetExpenseSystem.Api.dll"]
